/*
 * File: app/view/CamerasGridViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cameras.view.CamerasGridViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.camerasgrid',

    init: function() {
        let socket = new WebSocket("ws://localhost:8080/events/sub");

        socket.onopen = function(e) {
            console.log('onopen');
        };

        socket.onmessage = this.onMessage.bind(this);
    },

    onMessage: function(event) {
        let data = Ext.decode(event.data);

        let gridData = this.getView().getStore().getData();

        for(let i=0; i < gridData.length; i++) {
            let checked = gridData.getAt(i).get("checked");

            if(checked !== undefined && checked) {
                if(gridData.getAt(i).get("id") == data.camera.id) {
                    this.fireViewEvent("cameraRecognition", Ext.create("Cameras.model.EventsModel", data));
                }
            }
        }
    }

});