/*
 * File: app/view/CamerasGrid.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cameras.view.CamerasGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.camerasgrid',

    requires: [
        'Cameras.view.CamerasGridViewController',
        'Ext.grid.column.Check'
    ],

    controller: 'camerasgrid',
    itemId: 'mygrid',
    name: 'CamerasGrid',
    store: 'CamerasStore',

    columns: [
        {
            xtype: 'checkcolumn',
            itemId: 'checkcolumn',
            width: 50,
            dataIndex: 'checked',
            text: ''
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'id',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'name',
            text: 'Name'
        }
    ]

});