/*
 * File: app/model/EventsModel.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cameras.model.EventsModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],


    fields: [
        {
            type: 'string',
            convert: function(v, rec) {
                if(v !== undefined) {
                    rec.data.cameraId = "" + v.id;
                    return v;
                }
            },
            name: 'camera'
        },
        {
            type: 'date',
            convert: function(v, rec) {
                console.log(v, rec);
                return Ext.Date.format(new Date(v), "H:i:s")
            },
            name: 'added'
        },
        {
            name: 'cameraId'
        }
    ]

});